{% set name = "csvlint" %}
{% set version = "1.2.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 886c87441af105065e620386434ae2cd9d9c69cfcd532335ae52f1cd15f419c8

build:
  noarch: generic
  number: 1
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3
    - rb-rainbow
    - rb-open_uri_redirections
    - rb-activesupport
    - rb-addressable
    - rb-typhoeus
    - rb-escape_utils
    - rb-uri_template
    - rb-thor
    - rb-rack
    - rb-net-http-persistent
    - rb-concurrent-ruby <1.1

test:
  commands:
    - csvlint help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: A ruby gem to support validating CSV files to check their syntax and contents.
  doc_url: https://www.rubydoc.info/gems/csvlint
  dev_url: https://github.com/Data-Liberation-Front/csvlint.rb

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
